version: '3.8'

services:
  app:
    image: your_image_name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - ENV_VARIABLE_NAME=value
    volumes:
      - .:/app

# To run: docker-compose up